name: build

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bake.tex
          working_directory: spec/
          args: -jobname=bake -pdf -file-line-error -halt-on-error -interaction=nonstopmode
